import java.util.Scanner;
public class Binart_to_Octal 
{
    public static void main(String[] args) 
    {
    int[] a=new int[100];
        long b;
        int b1=0,i=0,n,p=0,re=0;
         Scanner r1=new Scanner(System.in);
           System.out.print("Enter the binary value:");
           b=r1.nextLong(); 
           System.out.println("1. Decimal\n2. octal\n3.Hexa decimal \n");
           System.out.print("Enter the value:");
           n=r1.nextInt();
           if(n==1)
           {
             while(b>0)
             {
                 long c=b%10;
                 re+=(int)(c*(Math.pow(2,p++)));
                 b=b/10;
             }       
              System.out.print(re);      
           }

           if(n==2)
           {
           while(b>0)
           {
            if(b%1000==0)
            {
               a[i++]=0;
                b=b/1000;
                b1++; 
            }
            if(b%1000==1)
            {
               a[i++]=1;
                b=b/1000;
                b1++; 
            }
            if(b%1000==10)
            {
               a[i++]=2;
                b=b/1000;
                b1++; 
            }
            if(b%1000==11)
            {
               a[i++]=3;
                b=b/1000;
                b1++; 
            }
             if(b%1000==100)
            {
                a[i++]=4;                
                b=b/1000;
                b1++; 
            }
             if(b%1000==101)
            {
                a[i++]=5;
                b=b/1000;
                b1++; 
            }
             if(b%1000==110)
            {
                a[i++]=6;
                b=b/1000;
                b1++; 
            }
             if(b%1000==111)
            {
                a[i++]=7;
                b=b/1000;
                b1++; 
            }            
        }
    }
        if(n==3)
        {
           while(b>0)
           {
            if(b%10000==0)
            {
               a[i++]=0;
                b=b/10000;
                b1++; 
            }
            if(b%10000==1)
            {
               a[i++]=1;
                b=b/10000;
                b1++; 
            }
            if(b%10000==10)
            {
               a[i++]=2;
                b=b/10000;
                b1++; 
            }
            if(b%10000==11)
            {
               a[i++]=3;
                b=b/10000;
                b1++; 
            }
             if(b%10000==100)
            {
                a[i++]=4;                
                b=b/10000;
                b1++; 
            }
             if(b%10000==101)
            {
                a[i++]=5;
                b=b/10000;
                b1++; 
            }
             if(b%10000==110)
            {
                a[i++]=6;
                b=b/10000;
                b1++; 
            }
             if(b%10000==111)
            {
                a[i++]=7;
                b=b/10000;
                b1++; 
            }
            if(b%10000==1000)
            {
                a[i++]=8;
                b=b/10000;
                b1++; 
            }
            if(b%10000==1001)
            {
                a[i++]=9;
                b=b/10000;
                b1++; 
            }
            if(b%10000==1010)
            {
                a[i++]=100;
                b=b/10000;
                b1++; 
            }
            if(b%10000==1011)
            {
                a[i++]=101;
                b=b/10000;
                b1++; 
            }
            if(b%10000==1100)
            {
                a[i++]=102;
                b=b/10000;
                b1++; 
            }
            if(b%10000==1101)
            {
                a[i++]=103;
                b=b/10000;
                b1++; 
            }
            if(b%10000==1110)
            {
                a[i++]=104;
                b=b/10000;
                b1++; 
            }
            if(b%10000==1111)
            {
                a[i++]=105;
                b=b/10000;
                b1++; 
            } 
          }
       }
             for(int j=b1-1;j>=0;j--)
            {
                if(a[j]==100)
                {
                    System.out.print('A');
                }
                if(a[j]==101)
                {
                    System.out.print('B');
                }
                if(a[j]==102)
                {
                    System.out.print('c');
                }
                if(a[j]==103)
                {
                    System.out.print('D');
                }
                if(a[j]==104)
                {
                    System.out.print('E');
                }
                if(a[j]==105)
                {
                    System.out.print('F');
                }
                if(a[j]>=0 && a[j]<=9)
                  System.out.print(a[j]);
            }
            r1.close();
    }
}
